### ISSUE TITLE
Using reference/create date

### ISSUE THREAD

**Issue by maifeng** [satya77/Transformer_Temporal_Tagger#1]
Hi, thank you for sharing the nice project and the paper. Is it possible to use reference dates for the examples in model_hub_seq2seq_examples.py? 

I also tried to use the tokenclassifier approach. But it seems that it does not provide a value in the tag.  Am I getting the expected output? 

https://github.com/satya77/Transformer_Temporal_Tagger/blob/81b92d0f0a958a37f8e4ebcb2de13430cfa73277/evaluation/classifier_generate_tempeval_data.py#L158
```

I lived in New York for <TIMEX3 tid="t28" type="DURATION" value="">10 years</TIMEX3>.
Cumbre Vieja last erupted in <TIMEX3 tid="t29" type="DATE" value="">1971</TIMEX3> and in <TIMEX3 tid="t30" type="DATE" value="">1949</TIMEX3>.
The club's founding date, <TIMEX3 tid="t31" type="DATE" value="">15 January</TIMEX3>, was intentional.
Officers were called to the house at 07:25 BST on <TIMEX3 tid="t32" type="DATE" value="">Sunday</TIMEX3> after concerns were raised about the people living there.
Police were first called to the scene just after <TIMEX3 tid="t33" type="TIME" value="">7</TIMEX3>.<TIMEX3 tid="t34" type="TIME" value="">25am this morning</TIMEX3>, <TIMEX3 tid="t35" type="DATE" value="">Sunday, September 19</TIMEX3>, and have confirmed they will continue to remain in the area for <TIMEX3 tid="t36" type="DATE" value="">some time</TIMEX3>.

```

Thanks again!

**Comment by dennlinger** [comment]
Hi @maifeng,
thanks for your interest in our work!

Unfortunately, at the current state of the work, we do not (yet) include any `VALUE` predicitions in the output, as the generated values from the Encoder-Decoder variants are not consistent.

We have previously experimented with prepending the reference date for cases like this, I will ping @satya77 to see if she can share more details on the experimental setup, and if there would be any way to get experimental values in the current networks at all.

**Comment by satya77** [comment]
Hi @maifeng, 
As @dennlinger pointed out the generated values are still not consistent but the seq2seq models generate them, while the token classifiers only generate a tag type. The script you are refering to parses the output of the classifers, which only predict the tags. If you want to look at the seq2seq models you need to look at this [script](https://github.com/satya77/Transformer_Temporal_Tagger/blob/81b92d0f0a958a37f8e4ebcb2de13430cfa73277/evaluation/seq2seq_generate_tempeval_data.py).

**Comment by dennlinger** [comment]
Hi @maifeng, just wanted to check in to see if this is still a persisting issue, or whether you have found a way to resolve this with the available code.
Otherwise I'd be closing the issue for now.

**Comment by maifeng** [comment]
Yes thank you for the answer.
