### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by dennlinger** [satya77/Transformer_Temporal_Tagger#3]
We should add a license to the project, to make it clear which use cases are legally allowed.
Depending on other dependencies, we might have to go with a specific license (e.g., transformers has parts licensed under Apache, I don't know how they affect each other).

**Comment by palak-jain** [comment]
Hello Satya,

I'm a researcher at Google. Exploring Bert-based temporal tagger to build a temporal reasoner for events. Could you please clarify the Licenses associated with your model usage.

Thanks

**Comment by dennlinger** [comment]
Hi @palak-jain ,
just letting you know that we've received your question, and are currently looking into this.
From what I can tell, there is a good chance that it will be licensed under either Apache/MIT, unless we find that some re-used parts of the evaluation pipeline would have a conflicting license (which I don't think is the case here).

I'll let you know once we've figured this out (1-2 days max).
Best,
Dennis

**Comment by dennlinger** [comment]
After some offline discussion with @satya77 , we've decided for an MIT license, as this should simplify usage of the project elsewhere.

FWIW, we've moved relevant code for the TempEval toolkit (previously in a separate folder in `temporal_taggers/evaluation/`) to a [different repository](https://github.com/dennlinger/python3-tempeval-toolkit), since the original code base does not specify a license, and therefore doesn't grant us the rights to re-license under our own terms. If you don't rely on the evaluation script, then this repository is now good to go :)
If you *do*, however, need the evaluation script as well, you unfortunately have to clarify with the [original tempeval3_toolkit repository's](https://github.com/naushadzaman/tempeval3_toolkit) author, who we couldn't reach through issues recently.

@palak-jain: Let me know if you have any additional questions about the project. Also, as a quick heads-up: We've noticed a bug in our seq2seq decoding, which means that the actual results are likely not as good as the previously reported ones. However, tagging models are not affected by this error, so you can still work with these model variants.

Best,
Dennis
