### ISSUE TITLE
examples/run_model_hub_taggers.py torch.cat() error when run with model_type = "date"

### ISSUE THREAD

**Issue by joshua-rubin** [satya77/Transformer_Temporal_Tagger#7]
The problem is caused by line 21:
`processed_date = torch.LongTensor(date_tokenizer(["2020 2 28" for _ in range(len(input_texts))], add_special_tokens=False)["input_ids"])`

It should be:
`processed_date = torch.LongTensor(date_tokenizer(["2020 2 28"], add_special_tokens=False)["input_ids"])`

You are processing each text individually in a loop, so this tensor should just contain the one item.

**Comment by satya77** [comment]
Thanks alot for the pointer I will fix this!
